allowed_domains: ['*']

# Object types should be singular nouns like 'comment' or 'team'
object_types: ['*']

user_roles:
  - admin
  - default
  # 'anonymous' is the implicit role for unauthenticated users

read_access_rules:
  objects:
    admin: ['*']
    default: ['*']
    anonymous: ['data.public']
  users:
    # 'self.default' means the current logged in user with role 'default', accessing their own user record.
    self.default: ['*','-roles']
    admin: ['*']
    default: ['*','-data.private','-roles']
    anonymous: ['data.public']

write_access_rules:
  objects:
    admin: ['*']
    default: ['*']
    anonymous: []
  users:
    self.default: ['*','-roles']
    admin: ['*']
    default: []
    anonymous:
      # 'anonymous' users can only create, i.e. sign up
      create: ['*','-roles']

defaults:
  users:
    roles: ['default']
    data:
      public: {}
      private: {}
